<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="petrinet" nsURI="http://petrinet" nsPrefix="pretinet">
  <eClassifiers xsi:type="ecore:EEnum" name="ArcKind">
    <eLiterals name="normal" literal="normal"/>
    <eLiterals name="read" value="1" literal="read"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//PetriNetElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PetriNetElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//PetriNetElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksToTarget" upperBound="-1"
        eType="#//Arc" eOpposite="#//Arc/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksToSource" upperBound="-1"
        eType="#//Arc" eOpposite="#//Arc/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="token" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arc" eSuperTypes="#//PetriNetElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/linksToSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/linksToTarget"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ArcKind"
        defaultValueLiteral="normal"/>
  </eClassifiers>
</ecore:EPackage>
