/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.idm.project.xtext.ShemaTablesRuntimeModule;
import fr.n7.idm.project.xtext.ShemaTablesStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ShemaTablesIdeSetup extends ShemaTablesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ShemaTablesRuntimeModule(), new ShemaTablesIdeModule()));
	}
	
}
