#!/bin/bash

# L'interface du réseau privé
ip link set dev eth0 up
ip a a 192.168.150.132/26 dev eth0

# L'interface du réseau public
ip link set dev eth1 up
ip a a 170.4.255.2/26 dev eth1

# Activer le forwarding
#echo 1 > /proc/sys/net/ipv4/ip_forward

# Le routage statique
#ip route add 170.4.255.64/26 via 170.4.255.3
#ip route add 170.4.255.128/26 via 170.4.255.3
#ip route add 170.4.255.192/26 via 170.4.255.3
#ip route add 192.168.150.192/26 via 170.4.255.4

# Activer le service DHCP
service isc-dhcp-server start

# Ajouter la route par défaut
ip route add default via 170.4.255.3

# Activer le NAT
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

# Filtrage

# Refuser tous les trafics
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Accepter le ping
iptables -A INPUT -p icmp -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT
iptables -A FORWARD -p icmp -j ACCEPT

# Accepter le trafic UDP du serveur DHCP
iptables -A INPUT -i eth0 -p udp --dport 67:68 --sport 67:68 -j ACCEPT

# Accepter le trafic UDP du serveur DNS
iptables -t filter -A FORWARD -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -p udp --sport 53 -j ACCEPT

# Accepter le trafic TCP du serveur HTTP
iptables -t filter -A FORWARD -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -p tcp --sport 80 -j ACCEPT

# Accepter le trafic TCP du serveur HTTPS
iptables -t filter -A FORWARD -p tcp --dport 443 -j ACCEPT
iptables -t filter -A FORWARD -p tcp --sport 443 -j ACCEPT











