#!/bin/bash

# L'interface du serveur DNS
ip link set dev eth0 up
ip a a 170.4.255.197/26 dev eth0

# Le routage statique
#ip route add 192.168.150.128/26 via 170.4.255.195
#ip route add 192.168.150.192/26 via 170.4.255.195
#ip route add 170.4.255.128/26 via 170.4.255.195
#ip route add 170.4.255.64/26 via 170.4.255.195
#ip route add 170.4.255.0/26 via 170.4.255.195

# Ajouter la route par défaut
ip route add default via 170.4.255.195

# Tuto : https://www.itzgeek.com/how-tos/linux/debian/configure-dns-server-on-debian-9-ubuntu-16-04.html?utm_content=cmp-true
# Activer le service BIND9
service bind9 start

# Ajouter la zone forward et la zone reverse au fichier named.conf.local
ZONES="
zone \"ayoubbouchama.com\" {
        type master;
        file \"/etc/bind/forward.ayoubbouchama.com\";
        allow-transfer { 170.4.255.197; };
        allow-update { none; };
 };

zone \"197.255.4.170.in-addr.arpa\" {
        type master;
        file \"/etc/bind/reverse.ayoubbouchama.com\";
        allow-transfer { 170.4.255.197; };
        allow-update { none; };
 };"

echo -e "$ZONES" >> "/etc/bind/named.conf.local"

# Créer les zones lockup file
# Zone Forward
ZONEFORWARD="
;
; BIND data file for local loopback interface
;
$TTL    604800
@       IN      SOA     www.ayoubbouchama.com. root.ayoubbouchama.com. (
			      6         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL
;
; Commentout below three lines
@      IN      NS      www.ayoubbouchama.com.
@      IN      A       170.4.255.197
www    IN      A       170.4.255.197
"
echo -e "$ZONEFORWARD" >> "/etc/bind/forward.ayoubbouchama.com"

# Zone Reverse
ZONEREVERSE="
;
; BIND data file for local loopback interface
;
\$TTL    604800
@       IN      SOA     www.ayoubbouchama.com. root.ayoubbouchama.com. (
                              5         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL

;
@       IN      NS      www.ayoubbouchama.com.
@       IN      PTR     ayoubbouchama.com.
www     IN  A           170.4.255.197
197     IN  PTR         www.ayoubbouchama.com.
"
echo -e "$ZONEREVERSE" >> "/etc/bind/reverse.ayoubbouchama.com"

# Les permissions
# Lecture et exécution pour tout le monde, écriture pour proriétaire seulement
chmod -R 755 /etc/bind

# changer le propriétaire du dossier bind
chown -R bind:bind /etc/bind



