/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ShemaTablesUiModule extends AbstractShemaTablesUiModule {

	public ShemaTablesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
